config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"


  resources :books, only: [:new, :index, :show, :create, :destroy, :edit]
  resources :users, only: [:edit, :show, :index, :edit, :update]
  patch 'books/:id' => 'books#update', as: 'update_book'
  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum:200 }
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum:50 }
  validates :name, uniqueness: true
  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
     flash[:notice] = "Welcome! You have signed in successfully."
     user_path(resource)
  end

  def after_sign_up_path_for(resource)
    flash[:notice] = "Welcome! You have signed up successfully."
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :name])
      devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :move_to_signed_in
  def new
    @book = Book.new
  end

  def index
    @books = Book.all
    @book= Book.new(params[:id])
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      render :index
    end
  end

  def show
    @books = Book.all
    @new_book = Book.new
    @book= Book.find(params[:id])
    @users = User.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

 private

  def authenticate_user!
     @book = Book.find(params[:id])
     unless @book.user == current_user
     redirect_to '/books'
     end
  end


def move_to_signed_in
    unless user_signed_in?
      redirect_to  '/users/sign_in'
    end
end
  def book_params
    params.require(:book).permit(:title, :body, :profile_image)
  end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_signed_in
  before_action :authenticate_user!, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @new_book = Book.new
  end

  def index
    @users = User.all
    @new_book = Book.new
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(current_user.id), notice: 'You have updated user successfully.'
    else
    render :edit
    end
  end

  private

  def authenticate_user!
    user = User.find(params[:id])
    if current_user != user
      redirect_to user_path(current_user.id)
    end
  end


def move_to_signed_in
    unless user_signed_in?
      redirect_to  '/users/sign_in'
    end
end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<body>
<h1>Editing Book</h1>
<p id="notice">
     <%= notice %>
  </p>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>
<p>本のタイトル</p>
<%= f.text_field :title %>
<p>感想</p>
<%= f.text_area :body %>
<div>
  <%= f.submit 'Update Book' %>
</div>
<%= link_to 'Show', book_path(@book.id) %>
<%= link_to 'Back', '/books'%>
<% end %>
</body>

app/views/books/index.html.erb
<head>
  <script src="https://kit.fontawesome.com/e37ce27edc.js" crossorigin="anonymous"></script>
</head>


<body>
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved: %>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div>
  <h2>User info</h2>

  <%= image_tag current_user.get_profile_image(63,63) %>

  <p><%= current_user.name %></p>
  <p>自己紹介文<%= current_user.introduction%></p>
  <%= link_to edit_user_path(current_user.id) do%>
   <i class="fas fa-user-cog"></i>
  <% end %>
  
</div>
<div>
<h2>New book</h2>
  <%= form_with model: @book, local:true do |f| %>

    <label>本のタイトル</label>
    <div>
      <%= f.text_field :title %>
    </div>

    <label>感想</label>
    <div>
      <%= f.text_area :body %>
    </div>
    <div><%= f.submit 'Create Book' %></div>

  <% end %>
  </div>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table table-striped">
    <div class="col-md-8 offset-md-1">
    <thead>
      <tr>
        <th></th>
        <th>本のタイトル</th>
        <th>感想</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.id) do %>
            <%= image_tag book.user.get_profile_image(40,40) %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
  </div>
</body>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<body>

  <p id="notice">
     <%= notice %>
  </p>

<div class="container">
<div class="row">
  <div class="col-md-3">
  <h2>User info</h2>
  <%= image_tag @book.user.get_profile_image(100,100) %>
  <p>名前<%= @book.user.name %></p>
  <p>自己紹介<%= @book.user.introduction%></p>

<%= link_to edit_user_path(@book.user) do%>
   <i class="fas fa-user-cog"></i>
<% end %>
<h2>New book</h2>
  <%= form_with model: @new_book, url:'/books', local:true do |f| %>
    <h4>本のタイトル</h4>
      <%= f.text_field :title %>
    <h4>感想</h4>
      <%= f.text_area :body %>
    <div>
      <%= f.submit 'Create Book' %>
    </div>
  <% end %>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table>
    <tbody>
      <tr>
        <td>
          <%= image_tag @book.user.get_profile_image(40,40) %>
          <%= link_to user_path(@book.user.id) do %></br>
          <%= @book.user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(@book.id) do %>
          <%= @book.title %>
          <% end %>
        </td>
        <td>
          <%= @book.body %>
        </td>
      </tr>
    </tbody>
  </table>
  </div>

  <% if @book.user == current_user %>
    <%= link_to "Edit", edit_book_path(@book)%>
    <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' } %>
  <% end %>
  </div>
  </div>
</body>

app/views/homes/about.html.erb
<head>
  <script src="https://kit.fontawesome.com/e37ce27edc.js" crossorigin="anonymous"></script>
</head>

<div class="welcome">
  <h1>Welcome to
   <i class="fas fa-book"></i><strong>Bookers!</strong>
  </h1>
</div>

app/views/homes/top.html.erb
<head>
  <script src="https://kit.fontawesome.com/e37ce27edc.js" crossorigin="anonymous"></script>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
  <h1>Welcome to
   <i class="fas fa-book"></i><strong>Bookers!</strong>
  </h1>

<p>you can share and exchange your opinions , inpressions , and emotions</p>
<p>about various books!</p>
  <div class="btn-wrapper col-10 mx-auto">
    <div class="row">
    <%= link_to "Log in", new_user_session_path %>
  </div>
  <div class="row">
    <%= link_to "Sign up", new_user_registration_path %>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>


    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column vh-100">
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a href="/">Bookers</a>
    <% if user_signed_in? %>
    <ul class="navbar-nav ml-auto">
      <li>
      <%= link_to user_path(current_user.id) do %>
      <i class="fas fa-home"></i>
      Home
      <% end %>
      </li>
      <li class="nav-item">
      <%= link_to '/users' do%>
      <i class="fas fa-users"></i>
      Users
      <% end %>
      </li>
      <li class="nav-item">
      <%= link_to '/books' do %>
      <i class="fas fa-book-open"></i>
      Books
      <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
        <i class="fas fa-sign-out-alt"></i>
        Log out
        <% end %>
      </li>
      </ul>
    <% else %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
      <%= link_to root_path  do %>
      <i class="fas fa-home"></i>
      Home
      <% end %>
      </li>
      <li>
      <%= link_to about_path do%>
      <i class="fas fa-link"></i>
      About
      <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_registration_path do%>
        <i class="fas fa-user-plus"></i>
        Sign up
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to new_user_session_path do%>
        <i class="fas fa-sign-in-alt"></i>
        Log in
        <% end %>
      </li>
    </ul>
    <% end %>
    </div>
    </nav>
  </header>
  <%= yield %>
  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>

</body>

</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<body>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"name"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.file_field :profile_image, placeholder: "Image_Id", accept: "image/*" %>
  <label for='inputIntroduction'>introduction</label>
  <%= f.text_field :introduction, id:"inputIntroduction", placeholder:"introduction"%>
  <%= f.submit "Update User" %>
<% end %>
</body>

app/views/users/index.html.erb
<body>
<div class="container mt-5">
<div class="row">
  <div class="col-md-3">
<div>
  <h2>User info</h2>
  <%= image_tag current_user.get_profile_image(63,63) %>

  <p><%= current_user.name %></p>
  <p>自己紹介文</p>
  <p><%= current_user.introduction%></p>
   
   <%= link_to edit_user_path(current_user.id) do%>
   <i class="fas fa-user-cog"></i>
   <% end %>
</div>
<div>
  <h2>New book</h2>
  <%= form_with model: @new_book, local:true do |f| %>
    <label>本のタイトル</label>
    <div>
      <%= f.text_field :title %>
    </div>
  </div>
  <div>
      <label>感想</label>
      <div>
        <%= f.text_area :body %>
      </div>
  </div>
    <div><%= f.submit 'Create Book' %></div>
  <% end %>
  </div>
<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>画像</th>
        <th>名前</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |users| %>
      <tr>
        <td><%= image_tag users.get_profile_image(40,40) %></td>
        <td><p><%= users.name %></p></td>
        <td><%= link_to 'Show', user_path(users.id)  %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
  </body>

app/views/users/show.html.erb
<body>
<div class="container px-5 px-sm-0">
<div class="row">
  <div class="col-md-3">

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
<div>
  <h2>User info</h2>
  <%= link_to user_path(@user.id) do %>
    <%= image_tag @user.get_profile_image(40,40) %>
  <% end %>


  <p><%= @user.name %></p>
  <p>自己紹介</p>
  <p><%= @user.introduction %></p>


    
  <%= link_to edit_user_path(@user) do%>
   <i class="fas fa-user-cog"></i>
   <% end %>
</div>
<div>
  <h2>New book</h2>
  <%= form_with model: @new_book, local:true do |f| %>

    <label>本のタイトル</label>
    <div>
      <%= f.text_field :title %>
    </div>
    <label>感想</label>
    <div>
      <%= f.text_area :body %>
    </div>
    <div><%= f.submit 'Create Book' %></div>
  <% end %>
</div>
</div>
<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-striped">
    <div class="col-md-8 offset-md-1">
    <thead>
      <tr>
        <th></th>
        <th>本のタイトル</th>
        <th>感想</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= image_tag @user.get_profile_image(40,40) %>
        </td>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
        </td>
        <td>
          <%= book.body %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>
</body>